import { createClient } from "npm:@supabase/supabase-js@2";
import { PDFDocument, StandardFonts, rgb } from "npm:pdf-lib@1.17.1";
const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8"};
const J=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:C});
const T=(v:unknown,f="")=>String(v??f).trim();
const url=Deno.env.get("SUPABASE_URL")||"", serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"", anonKey=Deno.env.get("SUPABASE_ANON_KEY")||"";
const sb=createClient(url,serviceKey);
const money=(v:any)=>new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"}).format(Number(v||0));
const dateIt=(v:any)=>{const s=T(v);if(!s)return "—";const d=new Date(s+"T00:00:00");return Number.isNaN(d.getTime())?s:d.toLocaleDateString("it-IT")};
async function makePdf(title:string,rows:[string,string][]) {const d=await PDFDocument.create(),p=d.addPage([595,842]),b=await d.embedFont(StandardFonts.HelveticaBold),r=await d.embedFont(StandardFonts.Helvetica);let y=785;p.drawRectangle({x:0,y:805,width:595,height:37,color:rgb(.06,.30,.51)});p.drawText("DELGROSSO VIAGGI & LIMOUSINE BUS",{x:35,y:818,size:15,font:b,color:rgb(1,1,1)});p.drawText(title,{x:35,y:y-35,size:18,font:b,color:rgb(.06,.30,.51)});y-=65;for(const [l,v] of rows){p.drawText(l.toUpperCase(),{x:35,y,size:8,font:b,color:rgb(.4,.45,.5)});p.drawText(T(v,"—"),{x:35,y:y-15,size:11,font:r,maxWidth:520});y-=42;if(y<65){p.addPage([595,842]);y=785}}return await d.save()}
async function admin(req:Request){const a=T(req.headers.get("authorization"));if(!/^bearer /i.test(a))return false;const token=a.slice(7).trim();const c=createClient(url,anonKey,{global:{headers:{Authorization:`Bearer ${token}`}}});const q=await c.rpc("is_gestionale_admin");return !q.error&&q.data===true}
async function recoverBooking(id:string){const q=await sb.from("prenotazioni").select("*").eq("id",id).maybeSingle();if(q.error)throw q.error;const b=q.data;if(!b)throw Error("Prenotazione non trovata");if(T(b.confirmation_storage_path))return{id,kind:"booking",status:"already_archived",path:b.confirmation_storage_path};const tq=await sb.from("viaggi").select("*").eq("id",b.viaggio_id).maybeSingle();if(tq.error)throw tq.error;const t=tq.data||{};const n=T(b.id_prenotazione||b.confirmation_number,`DG-P-${id.replace(/-/g,"").slice(0,8).toUpperCase()}`);const pdf=await makePdf("CONFERMA PRENOTAZIONE",[["Numero prenotazione",n],["Cliente",T(b.cliente_nome||b.cliente)],["Telefono",T(b.telefono)],["Email",T(b.email,"—")],["Viaggio",T(t.titolo||t.destinazione)],["Destinazione",T(t.destinazione)],["Data partenza",dateIt(t.data_partenza)],["Ora partenza",T(t.ora_partenza)],["Luogo partenza",T(t.luogo_partenza)],["Posti prenotati",T(b.posti,"—")],["Posti scelti",T(b.posti_selezionati,"—")],["Totale",money(b.totale)]]);const path=`conferme/${n}.pdf`;const up=await sb.storage.from("ricevute-prenotazioni").upload(path,pdf,{contentType:"application/pdf",upsert:true});if(up.error)throw up.error;const u=await sb.from("prenotazioni").update({confirmation_number:n,id_prenotazione:n,codice:n,confirmation_storage_path:path,confirmation_generated_at:new Date().toISOString()}).eq("id",id);if(u.error)throw u.error;return{id,kind:"booking",status:"archived",path}}
async function recoverPayment(id:string){const q=await sb.from("pagamenti").select("*").eq("id",id).maybeSingle();if(q.error)throw q.error;const p=q.data;if(!p)throw Error("Pagamento non trovato");if(T(p.receipt_storage_path))return{id,kind:"payment",status:"already_archived",path:p.receipt_storage_path};const bq=await sb.from("prenotazioni").select("*").eq("id",p.prenotazione_id).maybeSingle();if(bq.error)throw bq.error;const b=bq.data;if(!b)throw Error("Prenotazione collegata non trovata");const tq=await sb.from("viaggi").select("*").eq("id",b.viaggio_id).maybeSingle();if(tq.error)throw tq.error;const t=tq.data||{};const n=T(p.receipt_number,`DG-${String(p.data_pagamento||p.created_at||new Date().toISOString()).slice(0,4)}-${id.replace(/-/g,"").slice(0,8).toUpperCase()}`);const pdf=await makePdf(`RICEVUTA ${T(p.tipo,"ACCONTO").toUpperCase()}`,[['Numero ricevuta',n],["Cliente",T(b.cliente_nome||b.cliente)],["Viaggio",T(t.titolo||t.destinazione)],["Destinazione",T(t.destinazione)],["Data partenza",dateIt(t.data_partenza)],["Data pagamento",dateIt(p.data_pagamento)],["Metodo di pagamento",T(p.metodo_pagamento||p.metodo)],["Importo",money(p.importo)],["Totale prenotazione",money(p.totale||b.totale)],["Totale pagato",money(p.pagato)]]);const path=`pagamenti/${n}.pdf`;const up=await sb.storage.from("ricevute-prenotazioni").upload(path,pdf,{contentType:"application/pdf",upsert:true});if(up.error)throw up.error;const u=await sb.from("pagamenti").update({receipt_number:n,receipt_generated_at:new Date().toISOString(),receipt_storage_path:path,receipt_email_sent:false,receipt_email_sent_at:null,receipt_email_error:null}).eq("id",id);if(u.error)throw u.error;return{id,kind:"payment",status:"archived",path}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:C});if(req.method!=="POST")return J({success:false,error:"Metodo non consentito."},405);try{if(!(await admin(req)))return J({success:false,error:"Accesso negato: utente non autorizzato."},403);const p=await req.json().catch(()=>({}));const a=T(p.action,"missing");if(a==="missing"){const bq=await sb.from("prenotazioni").select("id").or("confirmation_storage_path.is.null,confirmation_storage_path.eq.").order("created_at",{ascending:true});if(bq.error)throw bq.error;const pq=await sb.from("pagamenti").select("id").or("receipt_storage_path.is.null,receipt_storage_path.eq.").order("created_at",{ascending:true});if(pq.error)throw pq.error;const results=[];for(const r of bq.data||[]){try{results.push(await recoverBooking(r.id))}catch(e){results.push({id:r.id,kind:"booking",status:"error",error:e instanceof Error?e.message:String(e)})}}for(const r of pq.data||[]){try{results.push(await recoverPayment(r.id))}catch(e){results.push({id:r.id,kind:"payment",status:"error",error:e instanceof Error?e.message:String(e)})}}return J({success:true,results,summary:{total:results.length,archived:results.filter(x=>x.status==="archived").length,already:results.filter(x=>x.status==="already_archived").length,errors:results.filter(x=>x.status==="error").length}})}if(a==="booking")return J({success:true,result:await recoverBooking(T(p.id))});if(a==="payment")return J({success:true,result:await recoverPayment(T(p.id))});return J({success:false,error:"Azione non valida."},400)}catch(e){return J({success:false,error:e instanceof Error?e.message:String(e)},500)}});
