
import {SITE_URL,SITE_KEY,H,siteGet,siteWrite} from './site.js';
const PASS='Delgrosso@26';const $=s=>document.querySelector(s);const show=(el,on)=>el.classList.toggle('hidden',!on);const msg=t=>{$('#msg').textContent=t};
function unlocked(){show($('#login'),false);show($('#app'),true);load()}
$('#loginForm').onsubmit=e=>{e.preventDefault();if($('#password').value.trim()!==PASS){msg('Password non corretta.');return}sessionStorage.setItem('dg_admin','1');unlocked()};$('#logout').onclick=()=>{sessionStorage.removeItem('dg_admin');location.reload()};
async function load(){try{const [m,f,c,g]=await Promise.all([siteGet('site_media','select=id'),siteGet('flotta_page','select=id'),siteGet('carousel_home','select=id'),siteGet('gallery_eventi','select=id')]);$('#s1').textContent=m.length;$('#s2').textContent=f.length;$('#s3').textContent=c.length;$('#s4').textContent=g.length;msg('Supabase SITO collegato correttamente.')}catch(e){msg('Supabase SITO: '+e.message)}}
$('#mediaForm').onsubmit=async e=>{e.preventDefault();try{const f=$('#mediaFiles').files;if(!f.length)throw new Error('Seleziona almeno una foto.');const cat=$('#mediaCat').value,title=$('#mediaTitle').value.trim()||'Media';let urls=[];for(const file of f){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${cat}/${Date.now()}-${Math.random().toString(36).slice(2,7)}-${safe}`;const r=await fetch(`${SITE_URL}/storage/v1/object/site-media/${path}`,{method:'POST',headers:{apikey:SITE_KEY,Authorization:`Bearer ${SITE_KEY}`,'Content-Type':file.type||'image/jpeg','x-upsert':'false'},body:file});if(!r.ok)throw new Error(await r.text());urls.push(`${SITE_URL}/storage/v1/object/public/site-media/${path}`)}const storagePath=urls[0].split('/site-media/')[1];
const row={category:cat,title,storage_path:storagePath,public_url:urls[0],sort_order:0,published:true};
await siteWrite('site_media',row);
if(cat==='carousel') await siteWrite('carousel_home',{titolo:title,foto_urls:urls,pubblicato:true,sort_order:0});
if(cat==='gallery' || cat==='party') await siteWrite('gallery_eventi',{titolo:title,data_evento:new Date().toISOString().slice(0,10),foto_urls:urls,pubblicato:true,sort_order:0});
$('#mediaForm').reset();msg(`${urls.length} foto caricate e sincronizzate nel Supabase SITO.`);load()}catch(e){msg(e.message)}};
$('#fleetForm').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);const urls=[];for(const file of $('#fleetFiles').files){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`fleet/${Date.now()}-${Math.random().toString(36).slice(2,7)}-${safe}`;const r=await fetch(`${SITE_URL}/storage/v1/object/site-media/${path}`,{method:'POST',headers:{apikey:SITE_KEY,Authorization:`Bearer ${SITE_KEY}`,'Content-Type':file.type||'image/jpeg'},body:file});if(!r.ok)throw new Error(await r.text());urls.push(`${SITE_URL}/storage/v1/object/public/site-media/${path}`)}if(!urls.length)throw new Error('Seleziona almeno una foto.');await siteWrite('flotta_page',{titolo:f.get('titolo'),descrizione:f.get('descrizione'),immagine_url:urls[0],foto_urls:urls,foto_gallery:urls,categoria:f.get('categoria'),posti:Number(f.get('posti')||0),pubblicato:true,attivo:true,sort_order:0});e.target.reset();msg('Mezzo pubblicato sul Supabase SITO.');load()}catch(e){msg(e.message)}};
if(sessionStorage.getItem('dg_admin')==='1')unlocked();
