const SUPABASE_URL='https://bhsanrbadsqcpbtxupmr.supabase.co';
const SUPABASE_KEY='sb_publishable_jcc3RIJmNnXZdhcmFuIKFg_EpxO_rBp';
const sb=window.DGPublicData.createClient(SUPABASE_URL,SUPABASE_KEY);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const media=arr=>Array.isArray(arr)?arr:[];
const fmtDate=d=>d?new Intl.DateTimeFormat(document.documentElement.lang==='en'?'en-GB':'it-IT',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00')):'';
function headerActive(){const p=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.navlinks a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===p));const h=document.querySelector('.site-header');const sync=()=>h?.classList.toggle('scrolled',scrollY>25);sync();window.addEventListener('scroll',sync,{passive:true});}
function mobileNav(){const b=document.querySelector('.mobile-toggle'),n=document.querySelector('.navlinks');if(!b||!n)return;b.setAttribute('aria-expanded','false');b.onclick=()=>{const open=n.classList.toggle('mobile-open');b.setAttribute('aria-expanded',String(open));b.textContent=open?'✕':'☰';};n.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{n.classList.remove('mobile-open');b.setAttribute('aria-expanded','false');b.textContent='☰';}));document.addEventListener('click',e=>{if(!n.contains(e.target)&&!b.contains(e.target)){n.classList.remove('mobile-open');b.setAttribute('aria-expanded','false');b.textContent='☰';}});}
async function loadSettings(){let {data}=await sb.from('site_settings').select('*').eq('id',1).maybeSingle();if(!data){let r=await sb.from('info_azienda').select('*').eq('id',1).maybeSingle();data=r.data?{company_name:r.data.nome,phone:r.data.telefono,whatsapp:r.data.whatsapp,email:r.data.email,address:r.data.indirizzo,instagram:r.data.instagram,facebook:r.data.facebook}:null;}return data||{};}
function applySettings(s){if(!window.DG_CONFIG?.contactsReady)return;s={...s,...Object.fromEntries(Object.entries(window.DG_CONFIG.contacts||{}).filter(([,v])=>v))};document.querySelectorAll('[data-setting]').forEach(el=>{const k=el.dataset.setting;if(s[k]){if(el.tagName==='A'&&(k==='phone'||k==='whatsapp'||k==='email'))el.href=k==='email'?`mailto:${s[k]}`:k==='whatsapp'?`https://wa.me/${String(s[k]).replace(/\D/g,'')}`:`tel:${String(s[k]).replace(/\s/g,'')}`;el.textContent=el.textContent.trim()&&k==='whatsapp'?'WhatsApp':s[k];}})}
function publicFleetItems(items){return (items||[]).filter(x=>! /mercedes|v\s*250|\bvan\b/i.test([x.title,x.marca,x.modello].filter(Boolean).join(" ")));}
function fleetCard(x,home=false){const imgs=media(x.gallery_urls);const cover=x.cover_url||imgs[0]||'';if(home)return `<a class="fleet-photo-card" href="flotta.html?bus=${encodeURIComponent(x.id)}" aria-label="Scopri ${esc(x.title)}"><img loading="lazy" src="${esc(cover)}" alt="${esc(x.title)}"><span class="fleet-open" aria-hidden="true">↗</span></a>`;return `<a class="fleet-card fleet-card-link" href="flotta.html?bus=${encodeURIComponent(x.id)}"><img loading="lazy" src="${esc(cover)}" alt="${esc(x.title)}"><div class="fleet-info"><h3>${esc(x.title)}</h3><p>${esc(x.description||'')} ${x.seats?`· ${x.seats} posti`:''}</p><span class="fleet-more">Vedi mezzo e galleria →</span></div></a>`;}
async function home(){
 const results=await Promise.allSettled([sb.from('carousel_home').select('*').eq('pubblicato',true).order('sort_order').order('created_at',{ascending:false}),getGestionaleTrips(),sb.from('site_fleet').select('*').eq('published',true).order('sort_order').order('created_at').limit(6),sb.from('site_party_events').select('*').eq('published',true).order('sort_order').order('created_at',{ascending:false}).limit(4),sb.from('site_posts').select('*').eq('published',true).order('sort_order').order('published_at',{ascending:false}).limit(3)]);
 const [c,v,f,p,posts]=results.map((result,index)=>result.status==='fulfilled'?result.value:(index===1?[]:{data:[]}));
 window.__dgTripsError=results[1].status==='rejected';
 const imgs=(c.data||[]).flatMap(x=>media(x.foto_urls)).filter(Boolean);const hero=document.querySelector('#heroMedia');if(hero){hero.innerHTML=imgs.length?imgs.map((u,i)=>`<img src="${esc(u)}" ${i?'loading="lazy"':''} class="${i?'':'show'}" alt="Del Grosso Viaggi">`).join(''):'<div class="hero-fallback"></div>';let i=0,els=[...hero.querySelectorAll('img')];if(els.length>1&&!document.body.classList.contains('home-dynamic'))setInterval(()=>{els[i]?.classList.remove('show');i=(i+1)%els.length;els[i]?.classList.add('show')},6000);}
 const tripsData=Array.isArray(v)?v:(v.data||[]);window.__dgTrips=tripsData;
 const dr=document.querySelector('#destinationRail');if(dr){const seen=new Map();tripsData.forEach(t=>{const name=(t.destinazione||t.titolo||'').trim();if(name&&!seen.has(name))seen.set(name,t)});const destinations=[...seen.entries()].slice(0,4);dr.innerHTML=destinations.length?destinations.map(([name,t])=>{const im=tripImage(t);return `<a class="destination-card" href="viaggi.html?dest=${encodeURIComponent(name)}">${im?`<img loading="lazy" src="${esc(im)}" alt="${esc(name)}">`:''}<div class="destination-copy"><small>Prossima esperienza</small><strong>${esc(name)}</strong><span>Scopri le partenze →</span></div></a>`}).join(''):'<div class="empty">Nuove destinazioni in arrivo.</div>';}
 const smartDest=document.querySelector('#smartDestination'),smartDate=document.querySelector('#smartDate'),smartAvail=document.querySelector('#smartAvailability');
 if(tripsData.length){const next=tripsData[0],a=gestTripAvailability(next);smartDest&&(smartDest.textContent=next.destinazione||next.titolo||'Prossima destinazione');smartDate&&(smartDate.textContent=fmtDate(next.data_partenza));smartAvail&&(smartAvail.innerHTML=`<span class="live-dot"></span>${a.soldOut?'Ultima disponibilità esaurita':'Disponibilità live'}`);const nx=document.querySelector('#nextExperience');if(nx){const ni=tripImage(next);nx.innerHTML=`<a class="next-experience-card" href="viaggio.html?id=${encodeURIComponent(next.id)}">${ni?`<img src="${esc(ni)}" alt="${esc(tripTitle(next))}">`:''}<div class="next-experience-shade"></div><div class="next-experience-copy"><div class="kicker">PROSSIMA ESPERIENZA · ${esc(tripCountdown(next.data_partenza,String(next.ora_partenza||'').slice(0,5)))}</div><h3>${esc(tripTitle(next))}</h3><p>${esc(next.destinazione||'Scopri la prossima partenza')}</p><span>Apri la scheda completa ↗</span></div><div class="next-experience-date"><b>${esc(String(next.data_partenza||'').slice(8,10)||'—')}</b><small>${esc(String(next.data_partenza||'').slice(5,7)||'')}</small></div></a>`;}}
 const tg=document.querySelector('#tripGrid');if(tg)tg.innerHTML=tripsData.length?tripsData.map(x=>tripCard(x)).join(''):`<div class="empty" style="grid-column:1/-1">Nessuna partenza pubblicata al momento.</div>`;startTripAutoRefresh('#tripGrid',6);
 const fg=document.querySelector('#fleetGrid');if(fg)fg.innerHTML=publicFleetItems(f.data).length?publicFleetItems(f.data).map(x=>fleetCard(x,true)).join(''):`<div class="empty">Flotta in aggiornamento.</div>`;
 const pe=document.querySelector('#partyPreview');if(pe){const first=(p.data||[])[0];pe.innerHTML=first?`<div class="party-feature"><div class="party-copy"><div class="eyebrow">Party on the Road</div><h2>${esc(first.title)}</h2><p>${esc(first.description||'Un’esperienza diversa, esclusiva e tutta da vivere a bordo.')}</p><div class="actions"><a class="btn btn-primary" href="partyontheroad.html">Scopri l'esperienza</a></div></div><div class="party-image" style="background-image:url('${esc(first.cover_url||media(first.gallery_urls)[0]||'')}')"></div></div>`:`<div class="empty">Nuovi eventi in arrivo.</div>`;}
 const pg=document.querySelector('#postGrid');if(pg)pg.innerHTML=(posts.data||[]).length?posts.data.map(x=>`<a class="news-card" href="news.html?id=${encodeURIComponent(x.id)}"><div class="news-card-img"><img loading="lazy" src="${esc(x.cover_url||'')}" alt="${esc(x.title)}"><span class="news-arrow">↗</span></div><div class="news-card-body"><div class="trip-date">${esc(x.category||'News')} · ${esc(fmtDate((x.published_at||'').slice(0,10)))}</div><h3>${esc(x.title)}</h3><p>${esc(x.excerpt||'Scopri la news completa.')}</p><span class="news-read">Leggi la news →</span></div></a>`).join(''):`<div class="empty" style="grid-column:1/-1">Nessuna news pubblicata al momento.</div>`;
 try{applySettings(await loadSettings())}catch(e){console.warn('Contatti non aggiornati',e)}
}
function tripImage(x){return x.locandina||x.immagine||x.cover_url||x.foto_url||'';}
function tripTitle(x){return x.titolo||x.destinazione||'Partenza Del Grosso';}
function tripField(x,...keys){for(const k of keys){if(x?.[k]!==undefined&&x?.[k]!==null&&String(x[k]).trim()!=='')return x[k]}return ''}
function tripCountdown(date,time=''){if(!date)return '';const t=String(time||'').slice(0,5);const d=new Date(`${date}T${t||'23:59'}:00`);if(Number.isNaN(d.getTime()))return '';const diff=d-new Date();if(diff<=0)return 'Partenza in corso';const days=Math.floor(diff/86400000),hours=Math.floor((diff%86400000)/3600000);return days>1?`Tra ${days} giorni`:days===1?'Domani':`Tra ${hours} ore`;}
function tripLongDate(d){if(!d)return '';return new Intl.DateTimeFormat(document.documentElement.lang==='en'?'en-GB':'it-IT',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date(`${d}T12:00:00`));}
function tripIcon(type){const icons={pin:'⌖',clock:'◷',bus:'▣',seat:'♢',price:'€',spark:'✦'};return icons[type]||'•';}
function tripCard(x){
 const a=typeof gestTripAvailability==='function'?gestTripAvailability(x):{soldOut:Number(x.posti_liberi??0)<=0,total:Number(x.posti_totali??0),free:Number(x.posti_liberi??0)};
 const sold=a.soldOut,known=a.known!==false,free=a.free,total=a.total,occupied=total&&known?Math.max(0,Math.min(total,total-free)):0,pct=total&&known?Math.round((occupied/total)*100):0;
 const img=tripImage(x),title=tripTitle(x),date=String(x.data_partenza||''),day=date.slice(8,10),mon=date.slice(5,7);
 const time=String(x.ora_partenza||'').slice(0,5),place=tripField(x,'luogo_partenza','punto_ritrovo','ritrovo','partenza');
 const price=(x.prezzo!==undefined&&x.prezzo!==null&&x.prezzo!=='')?`€ ${Number(x.prezzo).toFixed(0)}`:'Su richiesta';
 const status=sold?'SOLD OUT':!known?'DA VERIFICARE':free<=10?'ULTIMI POSTI':(x.stato||'DISPONIBILE');
 const countdown=tripCountdown(x.data_partenza,time);
 return `<article class="trip-card ${sold?'is-soldout':''}" data-trip-id="${esc(x.id)}">
  <a class="trip-card-click" href="viaggio.html?id=${encodeURIComponent(x.id)}" aria-label="Scopri ${esc(title)}">
   <div class="trip-img">${img?`<img loading="lazy" src="${esc(img)}" alt="${esc(title)}">`:'<div class="trip-img-placeholder">DELGROSSO<br>VIAGGI</div>'}
    <div class="trip-floating-date"><span>${esc(day||'—')}</span><small>${esc(mon||'')}</small></div>
    <div class="trip-card-topline"><span class="trip-live-pill"><i></i> LIVE</span><span class="trip-status ${sold?'sold':known&&free<=10?'soon':''}">${esc(status)}</span></div>
    <div class="trip-card-destination"><span>DESTINAZIONE</span><b>${esc(x.destinazione||title)}</b></div>
    ${sold?`<div class="soldout-overlay"><span>SOLD OUT</span><small>POSTI ESAURITI</small></div>`:''}
   </div>
  </a>
  ${sold?'<div class="soldout-strip">SOLD OUT · VIAGGIO AL COMPLETO</div>':''}
  <div class="trip-body">
   <div class="trip-card-kicker"><span>${esc(fmtDate(x.data_partenza))}</span>${countdown?`<span class="trip-countdown">${esc(countdown)}</span>`:''}</div>
   <div class="trip-title">${esc(title)}</div>
   <div class="trip-meta"><span class="trip-meta-main">⌖ ${esc(place||'Punto di partenza da comunicare')}</span><strong class="trip-price">${esc(price)}</strong></div>
   <div class="trip-meta"><span class="trip-meta-main">◷ ${esc(time||'—')}</span><strong class="availability ${!sold&&known&&free<=10?'low':''} ${sold?'none':''}">${sold?'POSTI ESAURITI':known?`${free} posti liberi${total?` / ${total}`:''}`:'Disponibilità da verificare'}</strong></div>
   ${total&&known?`<div class="availability-meter" aria-label="${pct}% posti occupati"><span style="width:${pct}%"></span></div><div class="trip-meter-label"><span>${pct}% occupato</span><span>${sold?'Completo':free<=10?'Affrettati':'Disponibilità live'}</span></div>`:''}
   <div class="trip-card-footer"><a class="btn btn-card-detail" href="viaggio.html?id=${encodeURIComponent(x.id)}">Scopri il viaggio <span>↗</span></a><a class="trip-book-mini ${sold?'disabled':''}" ${sold?'aria-disabled="true"':''} href="${sold?'viaggio.html?id='+encodeURIComponent(x.id):!known?'contatti.html':'prenota.html?viaggio='+encodeURIComponent(x.id)}">${sold?'Completo':known?'Prenota':'Informazioni'}</a></div>
  </div>
 </article>`;
}
async function tripDetail(){
 const root=document.querySelector('#tripDetail');if(!root)return;
 const id=new URLSearchParams(location.search).get('id');
 if(!id){root.innerHTML='<div class="detail-error"><b>Seleziona una partenza.</b><p>Apri una delle esperienze disponibili per vedere tutti i dettagli.</p><a class="btn btn-blue" href="viaggi.html">Esplora le partenze →</a></div>';return;}
 root.innerHTML='<div class="detail-loading"><span></span><b>Prepariamo la tua esperienza…</b><small>Sincronizzazione live con Del Grosso</small></div>';
 try{
  const trips=window.__dgTrips?.length?window.__dgTrips:await getGestionaleTrips();
  let trip=(trips||[]).find(x=>String(x.id)===String(id));
  if(!trip){root.innerHTML='<div class="detail-error"><b>Partenza non disponibile.</b><p>Potrebbe essere stata rimossa, completata o non essere più pubblicata.</p><a class="btn btn-blue" href="viaggi.html">Torna alle partenze</a></div>';return;}
  window.__dgCurrentTrip=trip;
  const a=gestTripAvailability(trip),img=tripImage(trip),title=tripTitle(trip),date=String(trip.data_partenza||''),time=String(trip.ora_partenza||'').slice(0,5);
  document.title=`${title} | Del Grosso Viaggi`;
  let layout=null;try{layout=await getBusLayout(id)}catch(e){console.warn('Layout bus non disponibile',e)}
  const bus=layout?.bus||{},busName=[tripField(bus,'marca'),tripField(bus,'modello')].filter(Boolean).join(' ')||tripField(trip,'autobus_nome','bus_nome','modello_bus','autobus_modello','bus_modello');
  const seats=Number(tripField(trip,'posti_totali')||layout?.posti_totali||0)||a.total||0,meeting=tripField(trip,'luogo_partenza','punto_ritrovo','ritrovo','partenza');
  const price=(trip.prezzo!==undefined&&trip.prezzo!==null&&trip.prezzo!=='')?`€ ${Number(trip.prezzo).toFixed(0)}`:'Su richiesta';
  const progress=a.total?Math.round(((a.total-a.free)/a.total)*100):0,count=tripCountdown(date,time),description=tripField(trip,'descrizione','note_pubbliche','dettagli','descrizione_breve','excerpt')||'Una partenza da vivere dall’inizio alla fine, con la comodità del viaggio organizzato e l’attenzione Del Grosso Viaggi.';
  const heroBg=img?`style="--detail-bg:url('${esc(img)}')"`:'';
  const shareText=encodeURIComponent(`${title} · ${tripLongDate(date)} — Del Grosso Viaggi`);
  root.innerHTML=`<div class="trip-detail-shell">
   <div class="detail-topbar"><a class="back-link detail-back" href="viaggi.html">← Tutte le partenze</a><div class="detail-top-actions"><button id="shareTrip" class="detail-icon-btn" type="button" title="Condividi viaggio">↗ <span>Condividi</span></button><a class="detail-icon-btn" href="prenota.html?viaggio=${encodeURIComponent(id)}">Prenota <span>→</span></a></div></div>
   <section class="trip-detail-hero" ${heroBg}>
    <div class="trip-detail-hero-image">${img?`<img src="${esc(img)}" alt="${esc(title)}">`:''}</div><div class="trip-detail-hero-shade"></div>
    <div class="trip-detail-hero-content"><div class="trip-detail-eyebrow"><span class="trip-live-pill"><i></i> DISPONIBILITÀ LIVE</span><span>${esc(tripLongDate(date))}</span></div><h1>${esc(title)}</h1><p>${esc(trip.sottotitolo||description)}</p><div class="trip-detail-hero-actions"><a class="btn ${a.soldOut?'btn-soldout':'btn-primary'}" href="${a.soldOut?'#':'prenota.html?viaggio='+encodeURIComponent(id)}">${a.soldOut?'Viaggio al completo':'Scegli il tuo posto'} <span>→</span></a><a class="btn btn-glass" href="#tripInfo">Scopri il programma ↓</a></div></div>
    <div id="tripLiveStatus" class="trip-detail-status ${a.soldOut?'sold':''}"><strong>${a.soldOut?'SOLD OUT':a.free<=10?'ULTIMI POSTI':'DISPONIBILE'}</strong><span>${a.soldOut?'Nessun posto libero':`${a.free} posti ancora disponibili`}</span>${count?`<small>${esc(count)}</small>`:''}</div>
   </section>
   <section class="trip-detail-stats"><div><small>${tripIcon('clock')} PARTENZA</small><strong>${esc(time||'—')}</strong><span>${esc(meeting||'Ritrovo da comunicare')}</span></div><div><small>${tripIcon('pin')} DESTINAZIONE</small><strong>${esc(trip.destinazione||title)}</strong><span>Esperienza Del Grosso</span></div><div><small>${tripIcon('price')} PREZZO</small><strong>${esc(price)}</strong><span>per persona</span></div><div id="tripLiveSeats"><small>${tripIcon('seat')} POSTI</small><strong>${a.soldOut?'0':a.free}</strong><span>disponibili su ${a.total||seats||'—'}</span></div></section>
   <section id="tripInfo" class="trip-detail-main"><div class="trip-detail-copy"><div class="kicker">L'esperienza</div><h2>Il viaggio<br><em>comincia qui.</em></h2><p>${esc(description)}</p>${trip.note?`<div class="detail-note"><b>Nota importante</b><span>${esc(trip.note)}</span></div>`:''}<div class="experience-grid"><div><span>01</span><b>Organizzato</b><small>Partenza e assistenza curate da Del Grosso.</small></div><div><span>02</span><b>Comfort</b><small>Viaggio in autobus Gran Turismo.</small></div><div><span>03</span><b>Posto garantito</b><small>Scegli il tuo sedile direttamente online.</small></div></div></div><aside class="trip-detail-side"><div class="detail-live-line"><i></i><span>Disponibilità sincronizzata</span><span>LIVE</span></div><div class="detail-side-head"><span>Posti disponibili</span><strong id="tripSideFree">${a.soldOut?'SOLD OUT':`${a.free}`}</strong></div><div class="detail-progress"><span id="tripSideProgress" style="width:${progress}%"></span></div><div class="detail-side-meta"><span><b>Data</b>${esc(fmtDate(date))}</span><span><b>Partenza</b>${esc(time||'—')}</span><span><b>Ritrovo</b>${esc(meeting||'—')}</span><span><b>Bus</b>${esc(busName||'Gran Turismo')}</span></div><a class="btn ${a.soldOut?'btn-soldout':'btn-blue'} detail-full-btn" href="${a.soldOut?'viaggi.html':'prenota.html?viaggio='+encodeURIComponent(id)}">${a.soldOut?'Scopri altre partenze':'Prenota ora'} <span>→</span></a><small class="secure-note">✓ Disponibilità sincronizzata con il Gestionale</small></aside></section>
   <section class="trip-timeline"><div class="kicker">Come si vive</div><h2>Quattro momenti.<br>Un'unica esperienza.</h2><div class="timeline"><div class="timeline-step"><span>01</span><div><b>Ritrovo</b><p>${esc(meeting||'Punto di ritrovo indicato nella conferma')}</p></div></div><div class="timeline-step"><span>02</span><div><b>Partenza</b><p>${esc(time||'Orario indicato nella conferma')}</p></div></div><div class="timeline-step"><span>03</span><div><b>In viaggio</b><p>Comfort Gran Turismo, organizzazione e assistenza.</p></div></div><div class="timeline-step"><span>04</span><div><b>${esc(trip.destinazione||'Destinazione')}</b><p>Arrivo e tempo per vivere l'esperienza.</p></div></div></div></section>
   ${busName||seats?`<section class="trip-bus-card"><div><div class="kicker">A bordo</div><h2>Il comfort<br>fa la differenza.</h2><p>${busName?`Viaggerai a bordo di <strong>${esc(busName)}</strong>.`:''}${seats?` ${esc(String(seats))} posti configurati per questa partenza.`:''}</p></div><div class="bus-card-icon">🚍</div></section>`:''}
   <div class="detail-final-cta"><div><span class="kicker">DELGROSSO LIVE</span><h2>${a.soldOut?"Cerchi un'altra partenza?":"Pronto a partire?"}</h2><p>${a.soldOut?'Scopri subito le prossime esperienze disponibili.':'Scegli il posto e completa la richiesta in pochi passaggi.'}</p></div><a class="btn btn-primary" href="${a.soldOut?'viaggi.html':'prenota.html?viaggio='+encodeURIComponent(id)}">${a.soldOut?'Esplora partenze':'Vai alla prenotazione'} →</a></div>
  </div>`;
  document.querySelector('#shareTrip')?.addEventListener('click',async()=>{try{if(navigator.share)await navigator.share({title:title,text:`${title} · ${tripLongDate(date)}`,url:location.href});else{await navigator.clipboard.writeText(location.href);const b=document.querySelector('#shareTrip');if(b){b.innerHTML='✓ <span>Link copiato</span>';setTimeout(()=>b.innerHTML='↗ <span>Condividi</span>',1800)}}}catch{}});
  const rel=document.querySelector('#relatedTrips');if(rel){const more=(trips||[]).filter(x=>String(x.id)!==String(id)).slice(0,3);rel.innerHTML=more.length?more.map(tripCard).join(''):'<div class="empty">Altre partenze in arrivo.</div>';}
  startTripDetailLive(id);
  applySettings(await loadSettings());
 }catch(e){console.error(e);root.innerHTML='<div class="detail-error"><b>Non riesco a caricare questa partenza.</b><p>Controlla la connessione e riprova tra poco.</p><a class="btn btn-blue" href="viaggi.html">Torna alle partenze</a></div>';}
}

function startTripDetailLive(id){
 if(window.__dgDetailTimer)clearInterval(window.__dgDetailTimer);
 const refresh=async()=>{try{const list=await getGestionaleTrips(),t=list.find(x=>String(x.id)===String(id));if(!t)return;const a=gestTripAvailability(t),status=document.querySelector('#tripLiveStatus'),side=document.querySelector('#tripSideFree'),bar=document.querySelector('#tripSideProgress'),seat=document.querySelector('#tripLiveSeats');if(status){status.classList.toggle('sold',a.soldOut);const strong=status.querySelector('strong'),sp=status.querySelector('span');if(strong)strong.textContent=a.soldOut?'SOLD OUT':a.free<=10?'ULTIMI POSTI':'DISPONIBILE';if(sp)sp.textContent=a.soldOut?'Nessun posto libero':`${a.free} posti ancora disponibili`;const sm=status.querySelector('small');if(sm)sm.textContent=tripCountdown(t.data_partenza,String(t.ora_partenza||'').slice(0,5));}if(side)side.textContent=a.soldOut?'SOLD OUT':a.free;if(bar)bar.style.width=`${a.total?Math.round(((a.total-a.free)/a.total)*100):0}%`;if(seat){const strong=seat.querySelector('strong'),span=seat.querySelector('span');if(strong)strong.textContent=a.soldOut?'0':a.free;if(span)span.textContent=`disponibili su ${a.total||'—'}`;}const bookingUrl='prenota.html?viaggio='+encodeURIComponent(id);const ctas=[['.detail-top-actions a','Prenota →','Altre partenze →'],['.trip-detail-hero-actions a:first-child','Scegli il tuo posto →','Viaggio al completo →'],['.detail-full-btn','Prenota ora →','Scopri altre partenze →'],['.detail-final-cta a','Vai alla prenotazione →','Esplora partenze →']];ctas.forEach(([selector,availableLabel,fullLabel])=>{const link=document.querySelector(selector);if(!link)return;link.href=a.soldOut?'viaggi.html':bookingUrl;link.textContent=a.soldOut?fullLabel:availableLabel;link.classList.toggle('btn-soldout',a.soldOut);});}catch(e){console.warn('Aggiornamento dettaglio non riuscito',e)}};
 window.__dgDetailTimer=setInterval(refresh,30000);
}
async function fleet(){const {data}=await sb.from('site_fleet').select('*').eq('published',true).order('sort_order').order('created_at');const g=document.querySelector('#fleetFull');if(!g)return;const id=new URLSearchParams(location.search).get('bus');if(id){const item=(data||[]).find(x=>String(x.id)===String(id));if(item){renderFleetDetail(item);applySettings(await loadSettings());return;}}
g.innerHTML=(data||[]).length?data.map(x=>fleetCard(x,false)).join(''):`<div class="empty">Nessun mezzo pubblicato.</div>`;applySettings(await loadSettings());}
function renderFleetDetail(x){const g=document.querySelector('#fleetFull');const imgs=[x.cover_url,...media(x.gallery_urls)].filter(Boolean);document.querySelector('.fleet-page-title')?.remove();g.className='fleet-detail';g.innerHTML=`<div class="fleet-detail-top"><a class="back-link" href="flotta.html">← Tutta la flotta</a><div class="fleet-detail-head"><div><div class="eyebrow">DELGROSSO FLOTTA</div><h2>${esc(x.title)}</h2><div class="fleet-pills">${x.seats?`<span>💺 ${x.seats} posti</span>`:''}<span>✓ Comfort e sicurezza</span><span>📸 ${imgs.length} foto</span></div></div><a class="btn btn-blue" href="preventivo.html">Richiedi preventivo →</a></div></div><div class="fleet-gallery">${imgs.map((u,i)=>`<button type="button" class="fleet-gallery-item ${i===0?'featured':''}" data-lightbox="${encodeURIComponent(u)}"><img loading="lazy" src="${esc(u)}" alt="${esc(x.title)} · foto ${i+1}"><span>↗</span></button>`).join('')}</div><div class="fleet-description"><div><div class="kicker">Scheda mezzo</div><h3>Scopri ${esc(x.title)}</h3></div><div class="fleet-description-text">${formatText(x.description||'Informazioni e dotazioni del mezzo.')}</div></div></div>`;setupLightbox();}
function formatText(t){return esc(t).split(/\n\n+/).map(p=>`<p>${p.replace(/\n/g,'<br>')}</p>`).join('')}
function setupLightbox(){let box=document.querySelector('#siteLightbox');if(!box){box=document.createElement('div');box.id='siteLightbox';box.className='site-lightbox';box.innerHTML='<button class="lightbox-close" aria-label="Chiudi">✕</button><button class="lightbox-prev" aria-label="Foto precedente">‹</button><img alt=""><button class="lightbox-next" aria-label="Foto successiva">›</button>';document.body.appendChild(box);box.addEventListener('click',e=>{if(e.target===box||e.target.classList.contains('lightbox-close'))closeLightbox();});}const buttons=[...document.querySelectorAll('[data-lightbox]')];let current=0;const urls=buttons.map(b=>decodeURIComponent(b.dataset.lightbox));const img=box.querySelector('img');const open=i=>{current=i;img.src=urls[current];box.classList.add('open');document.body.classList.add('lightbox-open');};buttons.forEach((b,i)=>b.onclick=()=>open(i));box.querySelector('.lightbox-prev').onclick=e=>{e.stopPropagation();open((current-1+urls.length)%urls.length)};box.querySelector('.lightbox-next').onclick=e=>{e.stopPropagation();open((current+1)%urls.length)};document.onkeydown=e=>{if(!box.classList.contains('open'))return;if(e.key==='Escape')closeLightbox();if(e.key==='ArrowLeft')open((current-1+urls.length)%urls.length);if(e.key==='ArrowRight')open((current+1)%urls.length)};function closeLightbox(){box.classList.remove('open');document.body.classList.remove('lightbox-open');}}
async function party(){const {data}=await sb.from('site_party_events').select('*').eq('published',true).order('sort_order').order('created_at',{ascending:false});const g=document.querySelector('#partyGallery');if(g)g.innerHTML=(data||[]).length?data.flatMap(e=>{const a=[e.cover_url,...media(e.gallery_urls)].filter(Boolean);return a.map((u,i)=>`<a class="gallery-item" href="${esc(u)}" target="_blank" rel="noopener"><img loading="lazy" src="${esc(u)}" alt="${esc(e.title)}"></a>`)}).join(''):`<div class="empty">Nessun evento pubblicato.</div>`;applySettings(await loadSettings());}
async function trips(){const g=document.querySelector('#tripFull');try{const data=await getGestionaleTrips();window.__dgTrips=data||[];g.innerHTML=(data||[]).length?data.map(tripCard).join(''):`<div class="empty">Nessuna partenza disponibile.</div>`;startTripAutoRefresh('#tripFull');}catch(e){console.error(e);g.innerHTML='<div class="empty">Non riesco a collegarmi al Gestionale. Riprova tra poco.</div>';}applySettings(await loadSettings());}
function startTripAutoRefresh(selector,limit=null){if(window.__dgTripRefreshTimer)clearInterval(window.__dgTripRefreshTimer);const refresh=async()=>{try{const data=await getGestionaleTrips();const list=limit?data.slice(0,limit):data;window.__dgTrips=data;if(typeof window.__dgTripRender==='function' && selector==='#tripFull'){window.__dgTripRender(data);return;}const g=document.querySelector(selector);if(g)g.innerHTML=list.length?list.map(tripCard).join(''):`<div class="empty">Nessuna partenza disponibile.</div>`;}catch(e){console.warn('Aggiornamento disponibilità non riuscito',e)}};window.__dgTripRefresh=refresh;window.__dgTripRefreshTimer=setInterval(refresh,30000);if(!window.__dgTripVisibilityBound){document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')window.__dgTripRefresh?.();});window.addEventListener('focus',()=>window.__dgTripRefresh?.(),{passive:true});window.__dgTripVisibilityBound=true;}}
async function newsPage(){const g=document.querySelector('#newsList');if(!g)return;try{const {data,error}=await sb.from('site_posts').select('*').eq('published',true).order('published_at',{ascending:false}).order('created_at',{ascending:false});if(error)throw error;const id=new URLSearchParams(location.search).get('id');if(id){const post=(data||[]).find(x=>String(x.id)===String(id));if(!post){g.innerHTML='<div class="empty">News non trovata.</div>';return;}document.title=`${post.title} | Del Grosso Viaggi`;g.innerHTML=`<article class="news-article"><a class="back-link" href="news.html">← Tutte le news</a><div class="news-article-grid"><div class="news-article-media">${post.cover_url?`<img src="${esc(post.cover_url)}" alt="${esc(post.title)}">`:''}</div><div class="news-article-head"><div class="trip-date">${esc(post.category||'News')} · ${esc(fmtDate((post.published_at||'').slice(0,10)))}</div><h2>${esc(post.title)}</h2><p>${esc(post.excerpt||'')}</p><div class="news-share"><button id="shareNews" class="btn btn-blue">Condividi ↗</button><a class="btn btn-ghost dark-btn" target="_blank" rel="noopener" href="https://wa.me/?text=${encodeURIComponent(post.title+' — '+location.href)}">WhatsApp</a></div></div></div><div class="news-body">${formatText(post.body||post.excerpt||'')}</div></article>`;document.querySelector('#shareNews')?.addEventListener('click',async()=>{try{if(navigator.share)await navigator.share({title:post.title,text:post.excerpt||'',url:location.href});else await navigator.clipboard.writeText(location.href);}catch{}});return;}g.innerHTML=(data||[]).length?data.map(x=>`<a class="news-row" href="news.html?id=${encodeURIComponent(x.id)}"><div class="news-row-img">${x.cover_url?`<img loading="lazy" src="${esc(x.cover_url)}" alt="${esc(x.title)}">`:''}</div><div><div class="trip-date">${esc(x.category||'News')} · ${esc(fmtDate((x.published_at||'').slice(0,10)))}</div><h2>${esc(x.title)}</h2><p>${esc(x.excerpt||'')}</p><span class="news-read">Leggi la news completa →</span></div><span class="news-row-arrow">↗</span></a>`).join(''):`<div class="empty">Nessuna news pubblicata al momento.</div>`;applySettings(await loadSettings());}catch(e){console.error(e);g.innerHTML='<div class="empty">Impossibile caricare le news. Riprova tra poco.</div>';}}
async function contacts(){applySettings(await loadSettings());}
headerActive();mobileNav();
function premiumMotion(){let bar=document.querySelector('.scroll-progress');if(!bar){bar=document.createElement('div');bar.className='scroll-progress';bar.innerHTML='<span></span>';document.body.appendChild(bar)}const progress=bar.querySelector('span');const sync=()=>{const h=document.documentElement.scrollHeight-window.innerHeight;progress.style.width=`${h>0?(scrollY/h)*100:0}%`};sync();window.addEventListener('scroll',sync,{passive:true});const media=document.querySelector('.hero-media');if(media && !matchMedia('(prefers-reduced-motion: reduce)').matches){media.classList.add('hero-parallax');window.addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*6,y=(e.clientY/innerHeight-.5)*4;media.style.transform=`scale(1.035) translate(${x}px,${y}px)`},{passive:true});}}
function siteUX(){const loader=document.querySelector('.page-loader');window.addEventListener('load',()=>setTimeout(()=>loader?.classList.add('hide'),180),{once:true});document.querySelectorAll('img').forEach((img,i)=>{if(i>0&&!img.loading)img.loading='lazy';img.decoding='async';});if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');observer.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -35px'});document.querySelectorAll('.section-head,.trip-card,.fleet-card,.fleet-photo-card,.news-card,.news-row,.party-feature,.contact-card,.gallery-item,.quote,.trip-toolbar').forEach(el=>{el.classList.add('reveal');observer.observe(el)});}}

/* =========================================================
   FLAGSHIP 2026 — single public UX layer
   Keeps all Supabase / booking / trip core functions above unchanged.
   ========================================================= */
(function DGFlagship(){
  const qs=(s,r=document)=>r.querySelector(s), qsa=(s,r=document)=>[...r.querySelectorAll(s)];
  const cfg=window.DG_CONFIG||{};
  const state={searchReady:false};

  function addSkip(){
    if(qs('.v10-skip'))return;
    const main=qs('main'); if(main&&!main.id)main.id='main-content';
    const a=document.createElement('a');a.className='v10-skip';a.href='#main-content';a.textContent='Vai al contenuto';document.body.prepend(a);
  }
  function breadcrumbs(){
    const main=qs('main');if(!main||qs('.v11-breadcrumb')||document.body.classList.contains('home-dynamic'))return;
    const path=(location.pathname.split('/').pop()||'index.html').toLowerCase();
    const labels={'viaggi.html':'Viaggi e partenze','prenota.html':'Prenota','viaggio.html':'Dettaglio viaggio','flotta.html':'Flotta','limousine.html':'Limousine Bus','noleggio.html':'Noleggio Bus','partyontheroad.html':'Party on the Road','chi-siamo.html':'Chi siamo','contatti.html':'Contatti','preventivo.html':'Preventivo','news.html':'Blog e news','privacy.html':'Privacy','cookie.html':'Cookie'};
    if(!labels[path])return;
    const b=document.createElement('div');b.className='v11-breadcrumb wrap';b.innerHTML=`<a href="index.html">Home</a><span>›</span><span>${labels[path]}</span>`;main.prepend(b);
  }
  function backTop(){
    if(qs('.flagship-backtop'))return;
    const b=document.createElement('button');b.className='flagship-backtop';b.type='button';b.setAttribute('aria-label','Torna in alto');b.textContent='↑';document.body.appendChild(b);
    const sync=()=>b.classList.toggle('show',scrollY>650);sync();addEventListener('scroll',sync,{passive:true});b.onclick=()=>scrollTo({top:0,behavior:'smooth'});
  }
  function socialFooter(){
    const footer=qs('footer');if(!footer||qs('.flagship-socials',footer))return;
    const social=(cfg.contactsExtra?.social||[]).filter(x=>x?.url&&/^https?:\/\//i.test(x.url));if(!social.length)return;
    const host=qs('.footer-brand',footer)||qs('.footer-grid>div',footer);if(!host)return;
    const wrap=document.createElement('div');wrap.className='flagship-socials';
    social.forEach(x=>{const a=document.createElement('a');a.href=x.url;a.target='_blank';a.rel='noopener';a.textContent=x.network==='Instagram'?'Instagram':'Facebook';a.setAttribute('aria-label',x.label||x.network);wrap.appendChild(a)});host.appendChild(wrap);
  }
  function mobileQuickbar(){
    let bar=qs('.mobile-quickbar');if(!bar){bar=document.createElement('div');bar.className='mobile-quickbar';bar.setAttribute('aria-label','Azioni rapide');document.body.appendChild(bar)}
    const wa=String(cfg.contacts?.whatsapp||'').replace(/\D/g,'');
    bar.innerHTML=`<a href="viaggi.html">Partenze</a><a href="prenota.html">Prenota</a>${wa?`<a href="https://wa.me/${wa}" target="_blank" rel="noopener">WhatsApp</a>`:`<a href="contatti.html">Contatti</a>`}`;
  }
  function injectSearchButton(){
    const nav=qs('.nav');if(!nav||qs('.flagship-search-button',nav))return;
    const b=document.createElement('button');b.type='button';b.className='flagship-search-button';b.setAttribute('aria-label','Cerca un viaggio');b.innerHTML='⌕';
    const toggle=qs('.mobile-toggle',nav);nav.insertBefore(b,toggle||null);b.onclick=()=>openSearch();
  }
  function makeSearch(){
    if(state.searchReady)return;state.searchReady=true;
    const o=document.createElement('div');o.className='flagship-search-overlay';o.setAttribute('aria-hidden','true');
    o.innerHTML=`<section class="flagship-search-panel" role="dialog" aria-modal="true" aria-label="Cerca un viaggio"><div class="flagship-search-head"><input id="flagshipSearchInput" type="search" autocomplete="off" placeholder="Cerca Napoli, Assisi, mercatini…"><button type="button" aria-label="Chiudi">×</button></div><div class="flagship-search-meta">Partenze ufficiali collegate al Gestionale · disponibilità aggiornata</div><div class="flagship-search-results"><div class="flagship-search-empty">Scrivi una destinazione oppure consulta le prossime partenze.</div></div></section>`;
    document.body.appendChild(o);o.addEventListener('click',e=>{if(e.target===o)closeSearch()});
    qs('button',o).onclick=closeSearch;qs('input',o).addEventListener('input',e=>renderSearch(e.target.value));
    document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSearch();if((e.key==='/'||((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'))&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)){e.preventDefault();openSearch();}});
  }
  async function openSearch(prefill=''){
    makeSearch();const o=qs('.flagship-search-overlay'),input=qs('#flagshipSearchInput',o);o.classList.add('open');o.setAttribute('aria-hidden','false');document.body.classList.add('flagship-search-open');input.value=prefill;
    if(!Array.isArray(window.__dgTrips)||!window.__dgTrips.length){try{window.__dgTrips=await getGestionaleTrips()}catch{window.__dgTrips=[]}}
    renderSearch(prefill);setTimeout(()=>input.focus(),30);
  }
  function closeSearch(){const o=qs('.flagship-search-overlay');if(!o)return;o.classList.remove('open');o.setAttribute('aria-hidden','true');document.body.classList.remove('flagship-search-open')}
  function renderSearch(q=''){
    const box=qs('.flagship-search-results');if(!box)return;const needle=q.trim().toLowerCase();
    const list=(window.__dgTrips||[]).filter(t=>!needle||(tripTitle(t)+' '+(t.destinazione||'')+' '+(t.luogo_partenza||'')).toLowerCase().includes(needle)).slice(0,12);
    if(!list.length){box.innerHTML='<div class="flagship-search-empty">Nessun viaggio trovato. <a href="viaggi.html">Apri tutte le partenze →</a></div>';return}
    box.innerHTML=list.map(t=>{const a=gestTripAvailability(t),img=tripImage(t),time=String(t.ora_partenza||'').slice(0,5);return `<a class="flagship-search-item" href="viaggio.html?id=${encodeURIComponent(t.id)}"><span class="flagship-search-thumb">${img?`<img src="${esc(img)}" alt="">`:''}</span><span class="flagship-search-copy"><small>${esc(fmtDate(t.data_partenza))}${time?' · '+esc(time):''}</small><b>${esc(tripTitle(t))}</b><span>${a.soldOut?'SOLD OUT':`${a.free} posti disponibili`}</span></span><strong>→</strong></a>`}).join('');
  }
  function homeCommand(){
    const root=qs('#homeLiveCommand');if(!root)return;const trips=Array.isArray(window.__dgTrips)?window.__dgTrips:[];
    if(!trips.length){root.innerHTML='<div class="empty">Il calendario delle partenze è in aggiornamento.</div>';return}
    const available=trips.filter(t=>!gestTripAvailability(t).soldOut),next=available[0]||trips[0],free=trips.reduce((n,t)=>n+gestTripAvailability(t).free,0),destinations=new Set(trips.map(t=>String(t.destinazione||'').trim().toLowerCase()).filter(Boolean)).size,a=gestTripAvailability(next),img=tripImage(next);
    root.innerHTML=`<div class="live-command-shell"><div class="live-command-main"><div class="command-label"><i></i> DELGROSSO LIVE · CALENDARIO UFFICIALE</div><h2>Partenze e disponibilità,<br>in un colpo d’occhio.</h2><p>Il sito legge il calendario operativo del Gestionale: quando aggiorni un viaggio, il pubblico vede date e disponibilità senza ricopiare i dati.</p><div class="command-stats"><div class="command-stat"><small>Partenze</small><b>${trips.length}</b></div><div class="command-stat"><small>Posti liberi</small><b>${free}</b></div><div class="command-stat"><small>Destinazioni</small><b>${destinations}</b></div></div><div class="actions" style="margin-top:22px"><a class="btn btn-primary" href="viaggi.html">Apri il calendario →</a></div></div><div class="live-command-next">${next?`<a class="command-next-card" href="viaggio.html?id=${encodeURIComponent(next.id)}">${img?`<img src="${esc(img)}" alt="${esc(tripTitle(next))}">`:''}<div class="command-next-date"><b>${esc(String(next.data_partenza||'').slice(8,10)||'—')}</b><small>${esc(String(next.data_partenza||'').slice(5,7)||'')}</small></div><div class="command-next-copy"><small>PROSSIMA PARTENZA · ${esc(tripCountdown(next.data_partenza,String(next.ora_partenza||'').slice(0,5)))}</small><b>${esc(tripTitle(next))}</b><span>${a.soldOut?'SOLD OUT':`${a.free} posti disponibili`} →</span></div></a>`:'<div class="empty">Nessuna partenza pubblicata.</div>'}</div></div>`;
  }
  function heroLive(){
    const trips=Array.isArray(window.__dgTrips)?window.__dgTrips:[],next=trips.find(t=>!gestTripAvailability(t).soldOut)||trips[0];if(!next)return;
    const a=gestTripAvailability(next),dest=qs('#smartDest'),date=qs('#smartDate'),avail=qs('#smartAvailability');
    if(dest)dest.textContent=tripTitle(next);if(date)date.textContent=fmtDate(next.data_partenza);if(avail)avail.textContent=a.soldOut?'Viaggio al completo':`${a.free} posti disponibili`;
  }
  function cardPolish(){
    qsa('.trip-card').forEach(card=>{if(card.dataset.flagship)return;card.dataset.flagship='1';const img=qs('.trip-img img',card);if(img){img.decoding='async';img.loading='lazy'}});
  }
  function structuredData(){
    if(qs('#dgStructuredData'))return;const sameAs=(cfg.contactsExtra?.social||[]).map(x=>x.url).filter(Boolean);const phone=cfg.contacts?.phone||cfg.contacts?.whatsapp||'';
    const data={'@context':'https://schema.org','@type':'Organization','name':'DELGROSSO Viaggi & Limousine Bus','url':'https://www.delgrossoviaggi.it/','logo':'https://www.delgrossoviaggi.it/assets/logo.JPEG','email':cfg.contacts?.email||undefined,'telephone':phone||undefined,'sameAs':sameAs.length?sameAs:undefined};
    Object.keys(data).forEach(k=>data[k]===undefined&&delete data[k]);const s=document.createElement('script');s.type='application/ld+json';s.id='dgStructuredData';s.textContent=JSON.stringify(data);document.head.appendChild(s);
  }
  function refresh(){homeCommand();heroLive();cardPolish()}
  function init(){
    document.body.classList.add('flagship-2026');addSkip();breadcrumbs();backTop();socialFooter();mobileQuickbar();injectSearchButton();makeSearch();structuredData();cardPolish();
    const heroSearch=qs('#flagshipHeroSearch');if(heroSearch)heroSearch.onclick=()=>openSearch();
    setTimeout(refresh,300);setTimeout(refresh,1200);
    const target=qs('#tripGrid')||qs('#tripFull');if(target&&'MutationObserver'in window)new MutationObserver(()=>{cardPolish();if(document.body.classList.contains('home-dynamic'))refresh()}).observe(target,{childList:true,subtree:true});
  }
  window.DGFlagship={refresh,openSearch};
  /* compatibility for inline calls that existed in older versions */
  window.v8Polish=()=>{cardPolish();refresh()};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();

siteUX();premiumMotion();
