const SUPABASE_URL='https://bhsanrbadsqcpbtxupmr.supabase.co';
const SUPABASE_KEY='sb_publishable_jcc3RIJmNnXZdhcmFuIKFg_EpxO_rBp';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const media=arr=>Array.isArray(arr)?arr:[];
const fmtDate=d=>d?new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00')):'';
function headerActive(){const p=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.navlinks a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===p));window.addEventListener('scroll',()=>document.querySelector('.site-header')?.classList.toggle('scrolled',scrollY>25),{passive:true});}
function mobileNav(){const b=document.querySelector('.mobile-toggle'),n=document.querySelector('.navlinks');if(!b||!n)return;b.onclick=()=>{n.style.display=n.style.display==='flex'?'none':'flex';n.style.position='absolute';n.style.top='72px';n.style.left='0';n.style.right='0';n.style.padding='20px';n.style.background='#07111f';n.style.flexDirection='column';n.style.alignItems='flex-start';};}
async function loadSettings(){let {data}=await sb.from('site_settings').select('*').eq('id',1).maybeSingle();if(!data){let r=await sb.from('info_azienda').select('*').eq('id',1).maybeSingle();data=r.data?{company_name:r.data.nome,phone:r.data.telefono,whatsapp:r.data.whatsapp,email:r.data.email,address:r.data.indirizzo,instagram:r.data.instagram,facebook:r.data.facebook}:null;}return data||{};}
function applySettings(s){document.querySelectorAll('[data-setting]').forEach(el=>{const k=el.dataset.setting;if(s[k]){if(el.tagName==='A'&&(k==='phone'||k==='whatsapp'||k==='email'))el.href=k==='email'?`mailto:${s[k]}`:k==='whatsapp'?`https://wa.me/${String(s[k]).replace(/\D/g,'')}`:`tel:${String(s[k]).replace(/\s/g,'')}`;el.textContent=s[k];}})}
async function home(){
 const [c,v,f,p,posts]=await Promise.all([
  sb.from('carousel_home').select('*').eq('pubblicato',true).order('sort_order').order('created_at',{ascending:false}),
  (typeof getGestionaleTrips==='function' ? getGestionaleTrips().then(x=>x.slice(0,6)) : sb.from('viaggi').select('*').eq('pubblicato','SI').order('data_partenza',{ascending:true}).limit(6).then(r=>r.data||[])),
  sb.from('site_fleet').select('*').eq('published',true).order('sort_order').limit(4),
  sb.from('site_party_events').select('*').eq('published',true).order('sort_order').order('created_at',{ascending:false}).limit(4),
  sb.from('site_posts').select('*').eq('published',true).order('sort_order').order('published_at',{ascending:false}).limit(3)
 ]);
 const imgs=(c.data||[]).flatMap(x=>media(x.foto_urls)).filter(Boolean);const hero=document.querySelector('#heroMedia');
 if(hero){hero.innerHTML=(imgs.length?imgs:[]).map((u,i)=>`<img src="${esc(u)}" ${i?'loading="lazy"':''} class="${i?'':'show'}" alt="Del Grosso Viaggi">`).join('');let i=0,els=[...hero.querySelectorAll('img')];if(els.length>1)setInterval(()=>{els[i]?.classList.remove('show');i=(i+1)%els.length;els[i]?.classList.add('show')},6000);}
 const tripsData=Array.isArray(v)?v:(v.data||[]); const tg=document.querySelector('#tripGrid');if(tg)tg.innerHTML=tripsData.length?tripsData.map(x=>tripCard(x)).join(''):`<div class="empty" style="grid-column:1/-1">Nessuna partenza pubblicata al momento.</div>`;
 const fg=document.querySelector('#fleetGrid');if(fg)fg.innerHTML=(f.data||[]).length?(f.data||[]).map(x=>`<a class="fleet-card" href="flotta.html"><img loading="lazy" src="${esc(x.cover_url||'')}" alt="${esc(x.title)}"><div class="fleet-info"><h3>${esc(x.title)}</h3><p>${esc(x.description||'Scopri il comfort e la qualità della nostra flotta.')}</p></div></a>`).join(''):`<div class="empty">Flotta in aggiornamento.</div>`;
 const pe=document.querySelector('#partyPreview');if(pe){const first=(p.data||[])[0];pe.innerHTML=first?`<div class="party-feature"><div class="party-copy"><div class="eyebrow">Party on the Road</div><h2>${esc(first.title)}</h2><p>${esc(first.description||'Un’esperienza diversa, esclusiva e tutta da vivere a bordo.')}</p><div class="actions"><a class="btn btn-primary" href="partyontheroad.html">Scopri l'esperienza</a></div></div><div class="party-image" style="background-image:url('${esc(first.cover_url||media(first.gallery_urls)[0]||'')}')"></div></div>`:`<div class="empty">Nuovi eventi in arrivo.</div>`;}
 const pg=document.querySelector('#postGrid');if(pg&&posts.data?.length)pg.innerHTML=posts.data.map(x=>`<article class="trip-card"><div class="trip-img"><img loading="lazy" src="${esc(x.cover_url||'')}" alt="${esc(x.title)}"></div><div class="trip-body"><div class="trip-date">${esc(x.category||'News')}</div><div class="trip-title">${esc(x.title)}</div><div class="trip-meta"><span>${esc(x.excerpt||'Scopri le novità Del Grosso Viaggi')}</span></div></div></article>`).join('');
 applySettings(await loadSettings());
}
function tripCard(x){const free=Number(x.posti_liberi??0),total=Number(x.posti_totali??0),sold=free<=0;const img=x.locandina||x.immagine||'';return `<article class="trip-card"><div class="trip-img">${img?`<img loading="lazy" src="${esc(img)}" alt="${esc(x.titolo||x.destinazione)}">`:''}</div><div class="trip-body"><div style="display:flex;justify-content:space-between;gap:8px;align-items:center"><div class="trip-date">${esc(fmtDate(x.data_partenza))}</div><span class="trip-status ${sold?'sold':''}">${sold?'Esaurito':esc(x.stato||'Confermato')}</span></div><div class="trip-title">${esc(x.titolo||x.destinazione)}</div><div class="trip-meta"><span>📍 ${esc(x.destinazione||'')}</span><strong class="trip-price">€ ${Number(x.prezzo||0).toFixed(0)}</strong></div><div class="trip-meta"><span>🕐 ${esc(String(x.ora_partenza||'').slice(0,5))} · ${esc(x.luogo_partenza||'')}</span><strong class="availability ${!sold&&free<=10?'low':''} ${sold?'none':''}">${sold?'Posti esauriti':`${free} posti liberi${total?` / ${total}`:''}`}</strong></div><div class="actions" style="margin-top:16px"><a class="btn btn-blue" href="prenota.html?viaggio=${encodeURIComponent(x.id)}">${sold?'Dettagli viaggio':'Prenota i posti'}</a></div></div></article>`} 

async function fleet(){const {data}=await sb.from('site_fleet').select('*').eq('published',true).order('sort_order').order('created_at');const g=document.querySelector('#fleetFull');g.innerHTML=(data||[]).length?data.map(x=>`<article class="fleet-card"><img loading="lazy" src="${esc(x.cover_url||'')}" alt="${esc(x.title)}"><div class="fleet-info"><h3>${esc(x.title)}</h3><p>${esc(x.description||'')} ${x.seats?`· ${x.seats} posti`:''}</p></div></article>`).join(''):`<div class="empty">Nessun mezzo pubblicato.</div>`;applySettings(await loadSettings());}
async function party(){const {data}=await sb.from('site_party_events').select('*').eq('published',true).order('sort_order').order('created_at',{ascending:false});const g=document.querySelector('#partyGallery');g.innerHTML=(data||[]).length?data.flatMap(e=>{const a=[e.cover_url,...media(e.gallery_urls)].filter(Boolean);return a.map((u,i)=>`<a class="gallery-item" href="${esc(u)}" target="_blank"><img loading="lazy" src="${esc(u)}" alt="${esc(e.title)}"></a>`)}).join(''):`<div class="empty">Nessun evento pubblicato.</div>`;applySettings(await loadSettings());}
async function trips(){const g=document.querySelector('#tripFull');try{const data=await getGestionaleTrips();g.innerHTML=(data||[]).length?data.map(tripCard).join(''):`<div class="empty">Nessuna partenza disponibile.</div>`;}catch(e){console.error(e);g.innerHTML='<div class="empty">Non riesco a collegarmi al Gestionale. Riprova tra poco.</div>';}applySettings(await loadSettings());}
async function contacts(){applySettings(await loadSettings());}
headerActive();mobileNav();
