/* DEL GROSSO GESTIONALE V112 — resilient network/cache worker */
const CACHE='dg-gestionale-v148-final';
const SCOPE_URL=new URL('./',self.registration.scope), SCOPE=SCOPE_URL.pathname;
const PRECACHE=['assets/dg-v126-command-dock.css?v=126','assets/dg-v126-command-dock.js?v=126','assets/dg-v127-booking-confirm.css?v=127','assets/dg-v128-booking-actions.css?v=128','assets/dg-v125-professional-shell.css?v=125','assets/dg-v125-professional-shell.js?v=125','login.html','dashboard.html','viaggi.html','prenotazioni.html','prenotazione.html','clienti.html','dossier-cliente.html','flotta.html','pagamenti.html','preventivi.html','preventivi-nuovo.html','notifiche.html','checkin.html','statistiche.html','impostazioni.html','centro-operativo.html','noleggi-bus.html','agenda.html','archivio.html','index.html','setup-amministratori.html','economia.html','dossier-viaggio.html','assets/dg-v95-trip-dossier.css?v=95','assets/dg-v95-trip-dossier.js?v=95','manifest.json','assets/dg-supabase-sync-v4.js','assets/prenotazioni-DG148.js','assets/settingsService-DG147.js','assets/dg-v82-fortress.js','assets/dg-v82-fortress.css','assets/dg-v84-black-text.css','assets/dg-v84-black-text.js','assets/dg-v85-stability.css','assets/dg-v85-stability.js','assets/dg-v86-dossier.css','assets/dg-v86-dossier.js','assets/dg-v87-layout.css','assets/dg-v88-universal-layout.css','assets/dg-v89-ultimate-ui.css','assets/dg-v90-universal-polish.css','assets/dg-v90-universal-polish.js','assets/dg-v92-iphone-menu.css','assets/dg-v93-universal-command.css','assets/dg-v93-universal-command.js','assets/dg-v95-trip-dossier.css','assets/dg-v95-trip-dossier.js','assets/dg-v102-advanced.css','assets/dg-v102-advanced.js','assets/dg-v103-advanced.css?v=103','assets/dg-v105-precision.css?v=104','assets/dg-v103-advanced.js?v=103','assets/dg-v105-precision.css?v=104','assets/dg-v105-precision.js?v=104','assets/dg-v106-viaggi-2.css?v=106','assets/paymentReceiptService-v24.js','assets/dg-receipts-v24.js','assets/dg-receipt-download-v28.js','assets/bookingDocumentsService-v25.js','assets/dg-v109-payment-integrity.css?v=109','assets/dg-v114-universal-mobile.js?v=112','assets/dg-v114-universal-mobile.css?v=112','assets/dg-v94-business.js?v=111','assets/dg-v94-business.css?v=111','assets/dg-v124-duplicate-guard.css?v=125','assets/viaggi-v55-supabase.js?v=125'];
const timeoutFetch=(request,ms=6000)=>Promise.race([fetch(request,{cache:'no-store'}),new Promise((_,rej)=>setTimeout(()=>rej(new Error('network-timeout')),ms))]);
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>Promise.all(PRECACHE.map(p=>c.add(new URL(p,SCOPE_URL).href).catch(()=>{})))).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(u.origin!==self.location.origin||e.request.method!=='GET'||!u.pathname.startsWith(SCOPE))return;if(/\/rest\/|\/auth\/|\/functions\//.test(u.pathname))return;e.respondWith(timeoutFetch(e.request).then(r=>{if(r?.ok)caches.open(CACHE).then(c=>c.put(e.request,r.clone())).catch(()=>{});return r}).catch(()=>caches.match(e.request).then(r=>r||(u.pathname.endsWith('.html')?caches.match(new URL('login.html',SCOPE_URL).href):Response.error()))));});
self.addEventListener('push',e=>{let d={};try{d=e.data?e.data.json():{}}catch(_){d={title:'Del Grosso Viaggi',body:e.data?e.data.text():'Nuova notifica'}}e.waitUntil(self.registration.showNotification(d.title||'Nuova prenotazione',{body:d.body||'È arrivata una nuova notifica.',icon:new URL('assets/icon-512.png',SCOPE_URL).href,badge:new URL('assets/icon-512.png',SCOPE_URL).href,tag:d.tag||'dg-booking',renotify:true,data:{url:d.url||'prenotazioni.html'}}))});
self.addEventListener('notificationclick',e=>{e.notification.close();const t=new URL(e.notification.data?.url||'prenotazioni.html',SCOPE_URL).href;e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const c of list){if('focus'in c){c.navigate(t).catch(()=>{});return c.focus()}}return clients.openWindow(t)}))});
