import {getSupabase,signIn,signOut,getSession,isAdmin,uploadSiteFile,removeSiteFile} from './site-api.js';
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let currentUser=null;
const state={home:[],viaggi:[],fleet:[],party:[],posts:[]};
function msg(text,type='ok'){const e=$('#adminMessage')||$('#loginMessage');if(e){e.textContent=text;e.className=`admin-message ${type}`;setTimeout(()=>e.textContent='',6000);}const st=$('#syncStatus'),tx=$('#syncText');if(type==='error'&&st&&tx){st.classList.remove('online');tx.textContent='⚠ Sincronizzazione: errore';}}
function setSyncState(ok,text){const st=$('#syncStatus'),tx=$('#syncText');if(tx)tx.textContent=text;if(st){st.classList.toggle('online',!!ok);}}
function fileNames(input){return [...(input?.files||[])].map(f=>f.name.trim().toLowerCase());}
function assertNoDuplicateSelection(input){const names=fileNames(input);const dup=names.filter((n,i)=>names.indexOf(n)!==i);if(dup.length)throw new Error(`Immagini duplicate nella selezione: ${[...new Set(dup)].join(', ')}`);}
function safeUploadName(name=''){return String(name).replace(/[^a-zA-Z0-9._-]/g,'-').replace(/-+/g,'-').slice(0,70).toLowerCase()||'file';}
function basename(path=''){return String(path).split('/').pop().replace(/^\d+-[a-f0-9-]+-/i,'').toLowerCase();}
function inputExistingNames(rows=[]){return new Set(rows.flatMap(x=>[x.title,x.storage_path].filter(Boolean).map(basename)));}
function setButtonBusy(button,busy,label){if(!button)return;button.disabled=busy;if(busy){button.dataset.originalLabel=button.textContent;button.textContent='⏳ Elaborazione…';}else if(button.dataset.originalLabel){button.textContent=label||button.dataset.originalLabel;delete button.dataset.originalLabel;}}
function progressBox(){return $('#uploadProgress');}
function resetProgress(){const e=progressBox();if(!e)return;e.hidden=true;e.innerHTML='';}
function renderProgress(items){const e=progressBox();if(!e)return;e.hidden=false;e.innerHTML=items.map((x,i)=>`<div class=\"upload-item\"><div class=\"upload-item-head\"><b>${esc(x.name)}</b><span id=\"uploadStatus-${i}\">${esc(x.status||'In attesa')}</span></div><div class=\"upload-track\"><i id=\"uploadBar-${i}\" style=\"width:${Number(x.pct)||0}%\"></i></div></div>`).join('');}
function updateProgress(i,pct,status){const bar=document.getElementById(`uploadBar-${i}`),st=document.getElementById(`uploadStatus-${i}`);if(bar)bar.style.width=`${Math.max(0,Math.min(100,pct))}%`;if(st)st.textContent=status;}
async function showSelectedStatus(input,rows=[],folder=''){const files=[...(input?.files||[])];if(!files.length){resetProgress();return;}const names=inputExistingNames(rows);let storageNames=new Set();try{const {data}=await getSupabase().storage.from('site-media').list(folder,{limit:1000});storageNames=new Set((data||[]).map(x=>String(x.name||'').toLowerCase()));}catch{};const items=files.map(f=>{const n=basename(f.name);const exists=names.has(n)||storageNames.has(f.name.trim().toLowerCase())||storageNames.has(safeUploadName(f.name));const mb=(Number(f.size||0)/1024/1024).toFixed(1);return {name:f.name,pct:exists?100:0,status:exists?'✓ GIÀ INSERITO':`Pronto · ${mb} MB`};});renderProgress(items);}
async function assertNoDuplicateNames(input,existingRows=[],folder=''){
 assertNoDuplicateSelection(input);const names=fileNames(input);if(!names.length)return;
 const existing=new Set(existingRows.flatMap(x=>[x.title,x.storage_path,x.public_url,x.cover_url,...(Array.isArray(x.gallery_urls)?x.gallery_urls:[])].filter(Boolean).map(basename)));
 const conflicts=names.filter(n=>existing.has(n)||existing.has(safeUploadName(n)));
 if(conflicts.length)throw new Error(`Upload bloccato: esiste già un'immagine con lo stesso nome: ${[...new Set(conflicts)].join(', ')}`);
 // Also check the storage folder so duplicate filenames are blocked even if the DB row is missing.
 if(folder){const {data,error}=await getSupabase().storage.from('site-media').list(folder,{limit:1000});if(error)throw error;const storageNames=new Set((data||[]).map(x=>String(x.name||'').toLowerCase()));const c=names.filter(n=>storageNames.has(n)||storageNames.has(safeUploadName(n)));if(c.length)throw new Error(`Upload bloccato: nel deposito esiste già un'immagine con lo stesso nome: ${[...new Set(c)].join(', ')}`);}
}
async function refresh(){
 const sb=getSupabase();
 setSyncState(false,'Sincronizzazione Supabase sito in corso…');
 const [home,viaggi,fleet,party,posts]=await Promise.all([
  sb.from('site_media').select('*').eq('category','carousel').order('sort_order').order('created_at',{ascending:false}),
  sb.from('site_carousel_viaggi').select('*').order('sort_order').order('created_at',{ascending:false}),
  sb.from('site_fleet').select('*').order('sort_order').order('created_at',{ascending:false}),
  sb.from('site_party_events').select('*').order('sort_order').order('created_at',{ascending:false}),
  sb.from('site_posts').select('*').order('created_at',{ascending:false})
 ]);
 for(const [name,r] of [['Carousel Home',home],['Carousel Partenze',viaggi],['Flotta',fleet],['Party',party],['Post',posts]])if(r.error)throw new Error(`${name}: ${r.error.message}`);
 state.home=home.data||[];state.viaggi=viaggi.data||[];state.fleet=fleet.data||[];state.party=party.data||[];state.posts=posts.data||[];
 $('#countHome').textContent=state.home.length;$('#countViaggi').textContent=state.viaggi.length;$('#countFleet').textContent=state.fleet.length;$('#countParty').textContent=state.party.length;$('#countPosts').textContent=state.posts.length;renderLists();
}
function renderLists(){
 const media=x=>`<div class="admin-row"><img src="${esc(x.public_url||x.image_url||x.cover_url||'')}" alt=""><div><b>${esc(x.title||x.titolo||'Immagine')}</b><small>${esc(x.description||'')}</small></div><div class="row-actions"><button data-del="${x.id}" data-table="site_media">Elimina</button></div></div>`;
 $('#listHome').innerHTML=state.home.map(media).join('')||'<p class="muted">Nessuna immagine.</p>';
 $('#listViaggi').innerHTML=state.viaggi.map(x=>`<div class="admin-row"><img src="${esc(x.image_url||'')}" alt=""><div><b>${esc(x.title||'Carousel Partenze')}</b><small>${esc(x.subtitle||'')}</small></div><div class="row-actions"><button data-del="${x.id}" data-table="site_carousel_viaggi">Elimina</button></div></div>`).join('')||'<p class="muted">Nessuna immagine.</p>';
 $('#listFleet').innerHTML=state.fleet.map(x=>`<div class="admin-row"><img src="${esc(x.cover_url||'')}" alt=""><div><b>${esc(x.title)}</b><small>${esc(x.seats?x.seats+' posti':'')} ${esc(x.description||'')}</small></div><div class="row-actions"><button data-edit-fleet="${x.id}">Modifica</button><button data-del="${x.id}" data-table="site_fleet">Elimina</button></div></div>`).join('')||'<p class="muted">Nessun mezzo.</p>';
 $('#listParty').innerHTML=state.party.map(x=>`<div class="admin-row"><img src="${esc(x.cover_url||((x.gallery_urls||[])[0]||''))}" alt=""><div><b>${esc(x.title)}</b><small>${(x.gallery_urls||[]).length} foto</small></div><div class="row-actions"><button data-edit-party="${x.id}">Modifica</button><button data-del="${x.id}" data-table="site_party_events">Elimina</button></div></div>`).join('')||'<p class="muted">Nessun evento.</p>';
 $('#listPosts').innerHTML=state.posts.map(x=>`<div class="admin-row"><img src="${esc(x.cover_url||'')}" alt=""><div><b>${esc(x.title)}</b><small>${esc(x.category)} · ${x.published?'Pubblicato':'Bozza'}</small></div><div class="row-actions"><button data-edit-post="${x.id}">Modifica</button><button data-del="${x.id}" data-table="site_posts">Elimina</button></div></div>`).join('')||'<p class="muted">Nessun post.</p>';
}
async function uploadMany(input,folder,existing=[],label='Caricamento'){await assertNoDuplicateNames(input,existing,folder);const files=[...input.files];if(files.some(f=>!String(f.type||'').startsWith('image/')&&!/\.(jpe?g|png|webp|gif|heic|heif)$/i.test(f.name)))throw new Error('Seleziona solo immagini. Su iPhone puoi scegliere direttamente dalla Libreria Foto o da File.');const items=files.map(f=>({name:f.name,pct:0,status:'In attesa'}));renderProgress(items);const out=[];for(let i=0;i<files.length;i++){const f=files[i];updateProgress(i,0,`Caricamento ${i+1}/${files.length}…`);try{out.push(await uploadSiteFile(f,folder,p=>updateProgress(i,p,`${p}% · ${i+1}/${files.length}`)));updateProgress(i,100,'✓ Caricata');}catch(error){if(/già|esiste|exist|409|400/i.test(error.message||''))updateProgress(i,100,'✓ GIÀ INSERITO');throw error;}}return out}
async function insertChecked(table,row){const {error}=await getSupabase().from(table).insert(row);if(error)throw new Error(`${table}: ${error.message}`);}
async function saveHome(){const btn=$('#homeSave');setButtonBusy(btn,true);try{const files=await uploadMany($('#homeFiles'),'carousel-home',state.home,'Carousel Home');const start=state.home.length;for(let i=0;i<files.length;i++)await insertChecked('site_media',{category:'carousel',title:'DELGROSSO VIAGGI',storage_path:files[i].path,public_url:files[i].url,sort_order:start+i,published:true});$('#homeFiles').value='';await refresh();msg('Carousel Home aggiornato e sincronizzato con Supabase.');}finally{setButtonBusy(btn,false,'Carica immagini');setTimeout(resetProgress,1200);}}
async function saveViaggi(){const btn=$('#viaggiSave');setButtonBusy(btn,true);try{const files=await uploadMany($('#viaggiFiles'),'carousel-viaggi',state.viaggi);const start=state.viaggi.length;for(let i=0;i<files.length;i++)await insertChecked('site_carousel_viaggi',{title:'DELGROSSO PARTENZE',image_url:files[i].url,sort_order:start+i,published:true});$('#viaggiFiles').value='';await refresh();msg('Carousel Partenze aggiornato e sincronizzato con Supabase.');}finally{setButtonBusy(btn,false,'Carica immagini');setTimeout(resetProgress,1200);}}
let editingFleet=null,editingParty=null,editingPost=null;
async function saveFleet(){const btn=$('#fleetSave');setButtonBusy(btn,true);try{const files=await uploadMany($('#fleetFiles'),'flotta',editingFleet?[]:state.fleet);let gallery=editingFleet?.gallery_urls?[...editingFleet.gallery_urls]:[];gallery.push(...files.map(x=>x.url));const data={title:$('#fleetTitle').value.trim(),description:$('#fleetDescription').value.trim(),cover_url:gallery[0]||editingFleet?.cover_url||null,gallery_urls:gallery,seats:Number($('#fleetSeats').value)||null,published:$('#fleetPublished').checked,sort_order:Number($('#fleetOrder').value)||0};if(!data.title)throw new Error('Inserisci il nome del mezzo.');const q=editingFleet?getSupabase().from('site_fleet').update(data).eq('id',editingFleet.id):getSupabase().from('site_fleet').insert(data);const {error}=await q;if(error)throw new Error(`Flotta: ${error.message}`);resetFleet();await refresh();msg('Flotta salvata e sincronizzata con Supabase.');}finally{setButtonBusy(btn,false,'Salva mezzo');setTimeout(resetProgress,1200);}}
function resetFleet(){editingFleet=null;$('#fleetTitle').value='';$('#fleetDescription').value='';$('#fleetSeats').value='';$('#fleetOrder').value='0';$('#fleetPublished').checked=true;$('#fleetFiles').value='';$('#fleetCancel').hidden=true;}
async function saveParty(){const btn=$('#partySave');setButtonBusy(btn,true);try{const files=await uploadMany($('#partyFiles'),'party-on-the-road',editingParty?[]:state.party);let gallery=editingParty?.gallery_urls?[...editingParty.gallery_urls]:[];gallery.push(...files.map(x=>x.url));const data={title:$('#partyTitle').value.trim(),event_date:$('#partyDate').value||null,description:$('#partyDescription').value.trim(),cover_url:gallery[0]||editingParty?.cover_url||null,gallery_urls:gallery,published:$('#partyPublished').checked,sort_order:Number($('#partyOrder').value)||0};if(!data.title||!gallery.length)throw new Error('Inserisci titolo e almeno una foto.');const q=editingParty?getSupabase().from('site_party_events').update(data).eq('id',editingParty.id):getSupabase().from('site_party_events').insert(data);const {error}=await q;if(error)throw new Error(`Party: ${error.message}`);resetParty();await refresh();msg('Evento Party salvato e sincronizzato con Supabase.');}finally{setButtonBusy(btn,false,'Salva album Party');setTimeout(resetProgress,1200);}}
function resetParty(){editingParty=null;$('#partyTitle').value='';$('#partyDate').value='';$('#partyDescription').value='';$('#partyOrder').value='0';$('#partyPublished').checked=true;$('#partyFiles').value='';$('#partyCancel').hidden=true;}
async function savePost(){const btn=$('#postSave');setButtonBusy(btn,true);try{let cover=editingPost?.cover_url||null;if($('#postFile').files[0]){await assertNoDuplicateNames($('#postFile'),'posts',editingPost?[editingPost]:state.posts);cover=(await uploadSiteFile($('#postFile').files[0],'posts',p=>updateProgress(0,p,`${p}%`))).url;}const data={title:$('#postTitle').value.trim(),excerpt:$('#postExcerpt').value.trim(),body:$('#postBody').value.trim(),category:$('#postCategory').value.trim()||'News',cover_url:cover,published:$('#postPublished').checked,published_at:$('#postPublished').checked?(editingPost?.published_at||new Date().toISOString()):null,sort_order:Number($('#postOrder').value)||0};if(!data.title)throw new Error('Inserisci il titolo del post.');const q=editingPost?getSupabase().from('site_posts').update(data).eq('id',editingPost.id):getSupabase().from('site_posts').insert(data);const {error}=await q;if(error)throw new Error(`Post: ${error.message}`);resetPost();await refresh();msg('Post salvato e sincronizzato con Supabase.');}finally{setButtonBusy(btn,false,'Salva post');setTimeout(resetProgress,1200);}}
function resetPost(){editingPost=null;for(const id of ['postTitle','postExcerpt','postBody','postCategory','postOrder'])$('#'+id).value=id==='postCategory'?'News':id==='postOrder'?'0':'';$('#postPublished').checked=true;$('#postFile').value='';$('#postCancel').hidden=true;}
function openEditFleet(id){editingFleet=state.fleet.find(x=>x.id===id);if(!editingFleet)return;$('#fleetTitle').value=editingFleet.title;$('#fleetDescription').value=editingFleet.description||'';$('#fleetSeats').value=editingFleet.seats||'';$('#fleetOrder').value=editingFleet.sort_order||0;$('#fleetPublished').checked=editingFleet.published;$('#fleetCancel').hidden=false;scrollToForm('fleetCard');}
function openEditParty(id){editingParty=state.party.find(x=>x.id===id);if(!editingParty)return;$('#partyTitle').value=editingParty.title;$('#partyDate').value=editingParty.event_date||'';$('#partyDescription').value=editingParty.description||'';$('#partyOrder').value=editingParty.sort_order||0;$('#partyPublished').checked=editingParty.published;$('#partyCancel').hidden=false;scrollToForm('partyCard');}
function openEditPost(id){editingPost=state.posts.find(x=>x.id===id);if(!editingPost)return;$('#postTitle').value=editingPost.title;$('#postExcerpt').value=editingPost.excerpt||'';$('#postBody').value=editingPost.body||'';$('#postCategory').value=editingPost.category||'News';$('#postOrder').value=editingPost.sort_order||0;$('#postPublished').checked=editingPost.published;$('#postCancel').hidden=false;scrollToForm('postCard');}
function scrollToForm(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'center'});}
function storagePathFromUrl(value){if(!value)return null;const s=String(value);const marker='/site-media/';const i=s.indexOf(marker);if(i>=0)return decodeURIComponent(s.slice(i+marker.length).split('?')[0]);return s.includes('/')&& !/^https?:\/\//i.test(s) ? s.replace(/^\/+/, '') : null;}
function collectStoragePaths(row){const values=[row?.storage_path,row?.public_url,row?.cover_url,...(Array.isArray(row?.gallery_urls)?row.gallery_urls:[])].filter(Boolean);return [...new Set(values.map(storagePathFromUrl).filter(Boolean))];}
async function deleteStoragePaths(paths){for(const path of paths)await removeSiteFile(path).catch(()=>{});}
async function del(table,id){if(!confirm('Eliminare definitivamente questo contenuto?'))return;const {data,error}=await getSupabase().from(table).select('storage_path,public_url,cover_url,gallery_urls').eq('id',id).maybeSingle();if(error)throw error;const {error:de}=await getSupabase().from(table).delete().eq('id',id);if(de)throw de;if(data)await deleteStoragePaths(collectStoragePaths(data));await refresh();msg('Contenuto eliminato.');}
async function deleteAllPhotos(section){
 const configs={
  home:{table:'site_media',filter:{category:'carousel'},label:'Carousel Home'},
  viaggi:{table:'site_carousel_viaggi',filter:null,label:'Carousel Partenze'},
  fleet:{table:'site_fleet',filter:null,label:'Flotta'},
  party:{table:'site_party_events',filter:null,label:'Party on the Road'},
  posts:{table:'site_posts',filter:null,label:'Post'}
 };
 const cfg=configs[section];if(!cfg)return;
 const scope=section==='home'?'del Carousel Home':section==='viaggi'?'del Carousel Partenze':section==='fleet'?'eliminare le foto della Flotta':section==='party'?'eliminare tutte le foto degli album Party':'eliminare le immagini dei Post';
 if(!confirm(`ATTENZIONE: vuoi ${scope}?\n\nQuesta operazione non può essere annullata.`))return;
 const sb=getSupabase();let q=sb.from(cfg.table).select('id,storage_path,public_url,cover_url,gallery_urls');if(cfg.filter)q=q.eq('category',cfg.filter.category);const {data,error}=await q;if(error)throw error;
 const rows=data||[];const paths=[...new Set(rows.flatMap(collectStoragePaths))];await deleteStoragePaths(paths);
 if(section==='home'){let d=sb.from(cfg.table).delete().eq('category','carousel');const r=await d;if(r.error)throw r.error;}
 else if(section==='viaggi'){const r=await sb.from(cfg.table).delete().gte('created_at','1970-01-01T00:00:00Z');if(r.error)throw r.error;}
 else if(section==='fleet'){for(const row of rows){const r=await sb.from(cfg.table).update({cover_url:null,gallery_urls:[]}).eq('id',row.id);if(r.error)throw r.error;}}
 else if(section==='party'){for(const row of rows){const r=await sb.from(cfg.table).update({cover_url:null,gallery_urls:[]}).eq('id',row.id);if(r.error)throw r.error;}}
 else if(section==='posts'){for(const row of rows){const r=await sb.from(cfg.table).update({cover_url:null}).eq('id',row.id);if(r.error)throw r.error;}}
 await refresh();msg(`Tutte le foto di ${cfg.label} sono state eliminate.`);
}
function bind(){
 const on=(id,event,fn)=>{const el=document.getElementById(id);if(el)el.addEventListener(event,fn);};
 on('loginForm','submit',async e=>{e.preventDefault();try{let login=$('#email').value.trim();if(login.toLowerCase()==='delgrosso@admin')login='info@delgrossoviaggi.it';const {error}=await signIn(login,$('#password').value);if(error)throw error;await boot();}catch(e){msg(e.message,'error')}});
 on('logout','click',async()=>{await signOut();location.reload()});
 const commands={homeSave:()=>saveHome(),viaggiSave:()=>saveViaggi(),fleetSave:()=>saveFleet(),partySave:()=>saveParty(),postSave:()=>savePost(),homeDeleteAll:()=>deleteAllPhotos('home'),viaggiDeleteAll:()=>deleteAllPhotos('viaggi'),fleetDeleteAll:()=>deleteAllPhotos('fleet'),partyDeleteAll:()=>deleteAllPhotos('party'),postDeleteAll:()=>deleteAllPhotos('posts')};
 for(const [id,fn] of Object.entries(commands)) on(id,'click',()=>fn().catch(e=>msg(e.message,'error')));
 on('fleetCancel','click',resetFleet);on('partyCancel','click',resetParty);on('postCancel','click',resetPost);
 document.addEventListener('click',e=>{const d=e.target.closest('[data-del]');if(d)del(d.dataset.table,d.dataset.del).catch(x=>msg(x.message,'error'));const f=e.target.closest('[data-edit-fleet]');if(f)openEditFleet(f.dataset.editFleet);const p=e.target.closest('[data-edit-party]');if(p)openEditParty(p.dataset.editParty);const n=e.target.closest('[data-edit-post]');if(n)openEditPost(n.dataset.editPost);});
 const fileMaps={homeFiles:['home','carousel-home'],viaggiFiles:['viaggi','carousel-viaggi'],fleetFiles:['fleet','flotta'],partyFiles:['party','party-on-the-road'],postFile:['posts','posts']};
 for(const id of Object.keys(fileMaps)){
  const input=document.getElementById(id);
  if(input) input.addEventListener('change',async e=>{try{assertNoDuplicateSelection(e.target);const [section,folder]=fileMaps[id];await showSelectedStatus(e.target,state[section]||[],folder);if(e.target.files.length)msg(`✓ ${e.target.files.length} file selezionat${e.target.files.length===1?'o':'i'}. Pronto per il caricamento.`);}catch(x){e.target.value='';resetProgress();msg(x.message,'error')}});
 }
 document.querySelectorAll('[data-pick]').forEach(btn=>btn.addEventListener('click',()=>{const input=document.getElementById(btn.dataset.pick);if(input){try{input.click();}catch(e){msg('Impossibile aprire la Libreria Foto. Riprova da Safari.','error');}}}));
 on('syncRefresh','click',()=>refresh().then(()=>msg('✓ Supabase del sito sincronizzato.')).catch(e=>msg(e.message,'error')));
}

async function boot(){const s=await getSession();if(!s){$('#login').hidden=false;$('#panel').hidden=true;return;}if(!(await isAdmin()))throw new Error('Questo account non è autorizzato come Admin del sito.');currentUser=s.user;$('#adminEmail').textContent=s.user.email;$('#login').hidden=true;$('#panel').hidden=false;await refresh();}
bind();boot().catch(e=>msg(e.message,'error'));
